name = "iss-location-project"
type = "javascript"
account_id = "your-account-id"
workers_dev = true
route = ""
zone_id = ""
usage_model = "bundled"
compatibility_date = "2023-05-18"

[site]
bucket = "./build"
entry-point = "."

[build]
command = "npm run build"